guest/routes.py
# index users/or guest users to site routes.py
from flask import Blueprint, render_template, flash
from airports import fetch_airports

guest_dashboard_bp = Blueprint('guest_dashboard_bp', __name__)

@guest_dashboard_bp.route('/airlin_admins', methods=['GET','POST'])
def airline_admins():
    # Logic or rendering for ticket in index page
    return render_template('airline_admins.html')

@guest_dashboard_bp.route('/ticket_index', methods=['GET', 'POST'])
def ticket_index():
    airports = fetch_airports()
    if airports is None: #to automatic airports retriving
        flash("An error occurred while fetching airports.")
    elif not airports:
        flash("No airports found.")
    return render_template('guest/ticket_index.html', airports=airports)

@guest_dashboard_bp.route('/tck_index', methods=['GET','POST'])
def ticket_index_su():
    # Logic or rendering for ticket in index page
    return render_template('guest/ticket_index_su.html')

@guest_dashboard_bp.route('/pnr_index', methods=['GET','POST'])
def pnr_index():
    # Logic or rendering for ticket in index page
    return render_template('guest/pnr_index.html')

@guest_dashboard_bp.route('/plane_schedule', methods=['GET','POST'])
def plane_schedule():
    # Logic or rendering for ticket in index page
    return render_template('guest/plane_schedule.html')

@guest_dashboard_bp.route('/user_register', methods=['GET','POST'])
def user_register():
    # Logic or rendering for ticket in index page
    return render_template('guest/user_register.html')

@guest_dashboard_bp.route('/register_success', methods=['GET','POST'])
def register_success():
    # Logic or rendering for ticket in index page
    return render_template('guest/register_success.html')

@guest_dashboard_bp.route('/instructions', methods=['GET','POST'])
def instructions():
    # Logic or rendering for ticket in index page
    return render_template('guest/instructions.html')

@guest_dashboard_bp.route('/newsevents_index', methods=['GET','POST'])
def newsevents_index():
    # Logic or rendering for ticket in index page
    return render_template('guest/newsevents_index.html')

@guest_dashboard_bp.route('/feedback_index', methods=['GET','POST'])
def feedback_index():
    # Logic or rendering for ticket in index page
    return render_template('guest/feedback_index.html')

@guest_dashboard_bp.route('/feedback_index_su', methods=['GET','POST'])
def feedback_index_su():
    # Logic or rendering for ticket in index page
    return render_template('guest/feedback_index_su.html')
# Uncomment and complete this route if needed
# @guest_dashboard_bp.route('/guest_pnr', methods=['GET'])
# def guest_pnr():
#     # Logic or rendering for guest PNR management page
#     return render_template('guest/guest_pnr.html')

# Additional routes for other guest functionalities

templates/adminlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>WELCOME ADMIN</title>
    <link href="style.css" rel="stylesheet" type="text/css">
</head>
<body>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    
   
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body {
        background-image: url('{{ url_for('static', filename='plane4.jpg') }}');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
</style>
<center>
    <form method="post" onsubmit="return login(this)" action="{{ url_for('admin_login_bp.admin_login') }}">
        <fieldset style="width:30%">
            <h3><center>ADMIN LOGIN</center></h3>
            <hr>
            <table>
                <tr>
                    <td>ADMIN NAME<font color="red">* </font>:</td>
                    <td> <input type="text" name="namem" id="name" placeholder="ADMIN NAME" required></td>
                </tr>
                <tr>
                    <td>ADMIN PASSWORD<font color="red">* </font>:</td>
                    <td><input type="password" name="passm" id="pass" placeholder="ADMIN PASSWORD" required></td>
                </tr>
                <tr>
                    <td></td>
                    <td>
                        <input type="submit" value="Login" name="s1" class="btn-primary">
                        <input type="reset" value="Reset" onclick="clearFunc()"class="btn-secondary">
                        <a href="{{ url_for('home') }}"><input type="button" value="Back" class="btn-secondary"></a>
                    </td>
                </tr>
            </table>
        </fieldset>
    </form>
    <br>

{% if error_message %}
    <h3 style="color: red;">{{ error_message }}</h3><//directly error message without the another error page>
{% endif %}
</center>

</body>
</html>

templates/airline_admins.html
<html>
	<head>
		<title>SKA AIRLINE ADMINS</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">

	</head>
	<body>
		<style>
			body {
				background-image: url('/static/plane21.jpg');
				background-repeat: no-repeat;
				background-attachment: fixed;
				background-size: cover;
			}
		</style>

<nav>
	<h3><font color="blue">THE ADMINS</font></h3>
   <ol type="a">
	<li><h4><font style="color:rgb(8, 111, 236)">SAI KIRAN</font></h4></li>
	<li><h4><font color="green">VANDANA</font></h4></li>
	<li><h4><font color="orange">RAMESH</font></h4></li>
	<li><h4><font style="color:rgb(11, 11, 238)">RAJITHA</font></h4></li>
	<center><button onclick=window.close() class="btn-primary"> CLOSE</button></center>

   </ol>
   </nav>
   </body>
   </html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Responsive Web Application{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}"> <!-- Your custom CSS -->
    {% block head %}{% endblock %}
</head>
<body>
    {% block content %}{% endblock %}
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script> <!-- Your custom JavaScript -->
    {% block scripts %}{% endblock %}
</body>
</html>

templates/error.html

  
<center><h3><font color="red">SORRY DB ERROR!</font></h3>
   
<p>{{error_message}}</p>
		   </center>

templates/index.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html>
	<head>
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<title>SKA AIRLINES.</title>

 </head>
 <script type="text/javascript">
	window.parentPage = true;
function ctck()
{
var sds = document.getElementById("dum");

}

</script>
<script type="text/javascript" src="\static\datetime2.js"></script>
<style>
    body {
        background-image: url('/static/plane2.jpg');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
    }
</style>
<style>
	body {margin:0;font-family:Arial}
	.topnav {
	  overflow: hidden;
	  background-color: #333;
	}
	.topnav a {
	  float: left;
	  display: block;
	  color: #f2f2f2;
	  text-align: center;
	  padding: 14px 16px;
	  text-decoration: none;
	  font-size: 17px;
	}
	
	.active {
	  background-color: #04AA6D;
	  color: white;
	}
	
	.topnav .icon {
	  display: none;
	}
	
	.dropdown {
	  float: left;
	  overflow: hidden;
	}
	
	.dropdown .dropbtn {
	  font-size: 17px;
	  border: none;
	  outline: none;
	  color: white;
	  padding: 14px 16px;
	  background-color: inherit;
	  font-family: inherit;
	  margin: 0;
	}
	
	.dropdown-content {
	  display: none;
	  position: absolute;
	  background-color: #f9f9f9;
	  min-width: 160px;
	  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
	  z-index: 1;
	}
	
	.dropdown-content a {
	  float: none;
	  color: black;
	  padding: 12px 16px;
	  text-decoration: none;
	  display: block;
	  text-align: left;
	}
	
	.topnav a:hover, .dropdown:hover .dropbtn {
	  background-color: #555;
	  color: white;
	}
	
	.dropdown-content a:hover {
	  background-color: #ddd;
	  color: black;
	}
	
	.dropdown:hover .dropdown-content {
	  display: block;
	}
	
	@media screen and (max-width: 600px) {
	  .topnav a:not(:first-child), .dropdown .dropbtn {
		display: none;
	  }
	  .topnav a.icon {
		float: right;
		display: block;
	  }
	}
	
	@media screen and (max-width: 600px) {
	  .topnav.responsive {position: relative;}
	  .topnav.responsive .icon {
		position: absolute;
		right: 0;
		top: 0;
	  }
	  .topnav.responsive a {
		float: none;
		display: block;
		text-align: left;
	  }
	  .topnav.responsive .dropdown {float: none;}
	  .topnav.responsive .dropdown-content {position: relative;}
	  .topnav.responsive .dropdown .dropbtn {
		display: block;
		width: 100%;
		text-align: left;
	  }
	}
	</style>



	<div class="topnav">

	  <a class="active" href="#home">HOME</a>

		 <a href="{{ url_for('admin_login_bp.admin_login') }}" target="_blank">ADMIN LOGIN</a>
	  <a href="{{ url_for('user_login_bp.user_login') }}" target="_blank">USER LOGIN</a>
	  <a href="{{ url_for('guest_dashboard_bp.ticket_index') }}"target="_blank">BOOK A TICKET</a>
	  <a href="{{ url_for('guest_dashboard_bp.pnr_index') }}"target="_blank">PNR STATUS</a>
	  <a href="{{ url_for('guest_dashboard_bp.plane_schedule') }}"target="_blank">PLANE SCHEDULE</a>
	  <a href="{{ url_for('guest_dashboard_bp.user_register') }}"target="_blank">REGISTER</a>
	  <div class="dropdown">
		<button class="dropbtn">ABOUT
		  <i class="fa fa-caret-down"></i>
		</button>
		<div class="dropdown-content">
			<a href="{{ url_for('guest_dashboard_bp.airline_admins') }}" target="_blank">AIRLINE ADMINS</a>
			<a href="{{ url_for('guest_dashboard_bp.instructions') }}" target="_blank">INSTRUCTIONS</a>
	        <a href="{{ url_for('guest_dashboard_bp.newsevents_index') }}" target="_blank">NEWS&Events</a>
	        <a href="{{ url_for('guest_dashboard_bp.feedback_index') }}" target="_blank">FEEDBACK</a>
	</div>
</div>
	  <font color="white"><a id="lblTime"></a></font>

		
		     <br>




<div id="footer_top">

    <br>


   </div>



    <script type="text/javascript">
    document.onload3 = ctck();

    </script>

    </div>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

/* Create two columns/boxes that floats next to each other */
nav {
  float: left;
  width: 40%;
  height: 200px; /* only for demonstration, should be removed */
  padding: 40px;
}

article {
  float: right;
  padding: 120px;
  width: 60%;
  height: 100px; /* only for demonstration, should be removed */
}

/* Clear floats after the columns */
section::after {
  content: "";
  display: table;
  clear: both;
}

/* Style the footer */
footer {
   padding:150px;
  text-align: center;
  color: white;
}



</style>

<body>

<section>
 
   <article>
    <h1><font size="100" Style="color:azure">SKA-AIRLINES</font></h1>
	<font size="6" Style="color:azure">Safety | Security | Punctuality</font>
	<br>
	<br>
</article>
</section>



   </body>
    </html>

templates/test.html
<!DOCTYPE html>
<html>
<head>
    <title>New Flight Form</title>
</head>
<body>
    <h1>Select Airport:</h1>
    <form method="POST" action="/submit_flight">
        <input list="dest" name="selected_airport" placeholder="Select an airport">
        <datalist id="dest">
            {% for airport in airports %}
            <option value="{{ airport[0] }}">{{ airport[0] }}</option>
            {% endfor %}
        </datalist>
        <br><br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/ticket_index.html
<!doctype html>
<html lang="en">
<head>
    <title>Airline Booking</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
    <script>
        function swapText() {
            var textBox1Value = document.getElementById("train1").value;
            var textBox2Value = document.getElementById("train2").value;
            document.getElementById("train1").value = textBox2Value;
            document.getElementById("train2").value = textBox1Value;
        }
    </script>
    <script>
        function login(form) {
            var t1 = document.getElementById("train1").value;
            var t2 = document.getElementById("train2").value;
            var doj = document.getElementById("doj").value;
            var tyc = document.getElementById("tyc").value;
            var tyb = document.getElementById("tyt").value;
            if (t1 == '') {
                alert("Please Select From");
                return false;
            } else if (t2 == '') {
                alert("Please select TO");
                return false;
            } else if (document.F1.train1.value == document.F1.train2.value) {
                alert("Your Selected Same Stations!");
                document.F1.train1.focus();
                document.F1.train2.value = "";
                return false;
            } else if (doj == '') {
                alert("Please select Date of Journey");
                return false;
            } else if (tyc == '') {
                alert("Please select Type of Ticket");
                return false;
            } else if (tyt == '') {
                alert("Please select Type of Booking");
                return false;
            }
        }
        function clearFunc() {
            document.getElementById("email").value = "";
            document.getElementById("pwd1").value = "";
        }
    </script>
    <style>
        body {
            background-image: url('/static/plane18.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }
        .transparent-button {
            background: transparent;
            border: none;
            cursor: pointer;
            padding: 0;
        }
        .clickable-img {
            cursor: pointer;
        }
    </style>
</head>
<body>
    <center>
        <form name="F1" method="POST" onSubmit="return login(this)" action="ticketbi.jsp">
            <fieldset style="width:32%; border-end-start-radius:25;">
                <h3>BOOK A TICKET</h3>
                <hr>
                <table>
                    <tr>
                        <td>
                            <img src="{{ url_for('static', filename='from2.png') }}" width="21" height="16">
                            <input list="source" name="SOURCE" id="train1" placeholder="ORIGIN">
                            <datalist id="source" name="train1">
                                {% for airport in airports %}
                                    <option value="{{ airport.airport_name }}">{{ airport.airport_name }}</option>
                                {% endfor %}
                            </datalist>
                        </td>
                        <td>
                            <script type="text/javascript">
                                window.onload = function() {
                                    var today = new Date().toISOString().split('T')[0];
                                    document.getElementsByName("setTodaysDate")[0].setAttribute('min', today);
                                }
                            </script>
                            <input name="setTodaysDate" type="date" id="doj">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                            <img src="{{ url_for('static', filename='updo.png') }}" alt="Arrow Up" width="20" height="20" onclick="swapText()" class="clickable-img">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <img src="{{ url_for('static', filename='to.jpg') }}" width="22" height="16">
                            <input list="source" name="dest" id="train2" placeholder="DESTINATION">
                            <datalist id="source" name="train1">
                                {% for airport in airports %}
                                    <option value="{{ airport.airport_name }}">{{ airport.airport_name }}</option>
                                {% endfor %}
                            </datalist>
                        </td>
                        <td>
                            <select name="tycl" id="tyc">
                                <option value="FIRST CLASS">FIRST CLASS</option>
                                <option value="BUSINESS CLASS">BUSINESS CLASS</option>
                                <option value="PREMIUM ECONOMY">PREMIUM ECONOMY</option>
                                <option value="ECONOMY">ECONOMY</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <br>
                            <script>
                                function showAlert() {
                                    var ld = document.getElementById("tyt").value;
                                    if (ld === "LADIES" || ld === "PHC") {
                                        alert("Specially abled passengers need to carry a Photo Identity card issued by the Government which is to be produced for On-board / Off-board verification during the journey.: " + ld);
                                    }
                                }
                            </script>
                            <label for="tyt">Type OF Ticket:</label>
                            <select name="tyt" id="tyt" onchange="showAlert()">
                                <option value="GENERAL">REGULAR</option>
                                <option value="LADIES">DEFENCE</option>
                                <option value="TATKAL">GOVT EMPLOYEE</option>
                                <option value="PREMIUM TATKAL">SENIOR CITIZEN</option>
                                <option value="PHC" id="phc">STUDENT</option>
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <td></td>
                    </tr>
                </table>
                <br>
                <input type="submit" value="BOOK" onClick="login(this.form)" class="btn-primary">
                <input type="reset" value="RESET" onclick="clearFunc()" class="btn-secondary">
                <a href="{{ url_for('home') }}"><input type="button" value="Back" class="btn-secondary"></a>
            </fieldset>
        </form>
        <br>
    </center>
    {% if error %}
    <p>{{ error }}</p>
{% endif %}
</body>
</html>

templates/userlogin.html
<!doctype html>
<html lang="en">
    <head>
        <title>Welcome To SKA AIRLINES</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">

    </head>
    <style>
        body {
            background-image: url('{{ url_for('static', filename='plane4.jpg') }}');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }
    </style>
    <body>


	<center>
        <form method = "post" onSubmit="return login(this)" action="{{ url_for('user_login_bp.user_login') }}">
            <fieldset style="width:24%">
                <h3><center>Train User Login</center></h3>
                <hr>
                <table>
                    <tr>
                        <td>USER NUMBER<font color="red">*</font>&nbsp:</td>
                        <td> <input type = "number" name = "number" id="number" Placeholder="USER NUMBER" required></td>
                    </tr>
                                        <tr>
                        <td>NAME<font color="red">*</font>&nbsp &nbsp&nbsp&nbsp&nbsp &nbsp &nbsp &nbsp &nbsp&nbsp &nbsp&nbsp:</td>
                        <td> <input type = "text" name = "name" id="name" Placeholder="USER NAME" required></td>
                    </tr>
                    <tr>
                        <td>PASSWORD<font color="red">* </font>&nbsp &nbsp &nbsp &nbsp:</td>
                        <td><input type = "password" name = "passc" id="pass"  Placeholder="PASSWORD" required></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><input type = "submit" value="login" name = "s1" onClick ="login(this.form)" class="btn-primary">
						<input type="reset" value="Reset" onclick="clearFunc()" class="btn-secondary">
						<a href="{{ url_for('home') }}""><input type="button" value="back" class="btn-secondary"></a>
						</td>
                    </tr>
                </table>
            </fieldset>
        </form>
		
        <br>
		{% if error_message %}
    <h3 style="color: red;">{{ error_message }}</h3><//directly error message without the another error page>
{% endif %}
</center>
	</body>
</html>